### ISSUE TITLE
Query editor font messed up after paste

### ISSUE THREAD

**Issue by fulldecent** [Sequel-Ace/Sequel-Ace#1153]
- Sequel Ace Version (including build number): Version 3.3.3 / Build 3034
- Sequel Ace Source (App Store/GitHub/Homebrew): App Store
- macOS Version: 11.4 (20F71)
- Processor Type (Intel/Apple): M1
- MySQL Version: n/a
- macOS Localization: en-US

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?** yes

**Description**

When editing in the query editor, especially when there are spaces indenting and copy/paste involved, the fonts will be messed up.

**Steps To Reproduce**
1.
2.

**Expected Behaviour**
All text in the text box will always be the same font and font size.

**Related Issues**
n/a

**Additional Context**

Font does not line up on columns. Monospace fonts should always line up on columns.

<img width="1528" alt="Screen Shot 2021-06-23 at 14 28 33" src="https://user-images.githubusercontent.com/382183/123149510-5801da80-d42f-11eb-9c68-8c9ea6a373a8.png">

**Comment by Jason-Morcos** [comment]
Maybe related: #487

**Comment by Jason-Morcos** [comment]
Just to be sure, can you share a screenshot of your font settings in Sequel Ace's Preferences, @fulldecent? I assume you have a monospaced font selected?

**Comment by fulldecent** [comment]
Can anyone else confirm this one?

**Comment by Maikel-Koek** [comment]
I also got font issues, sometimes when pasting, but mostly related to indenting; when indenting a line (with a tab), no issues, but after hitting enter, the tab of the next line seems to have a different font type, as you can see here in my screenshot below.
You can see the difference between the whitespace before `p.entity_id` and the lines below. The first one is correct, next ones aren't.
When commenting a line (using <kbd>Cmd</kbd> + <kbd>/</kbd>), the text _after_ the weird font-style tab is also converted to the new font, as you can see at `p.created_at`:

![Schermafbeelding 2021-08-05 om 16 40 49](https://user-images.githubusercontent.com/6301809/128369803-daaaff6c-ec0c-4169-868b-5e19055789fa.png)

Font settings:
![Schermafbeelding 2021-08-05 om 16 44 39](https://user-images.githubusercontent.com/6301809/128369907-925c22d2-c40d-4a9a-9bd8-315301873c3d.png)

I'm on OSX 11.4, using SequelAce Version 3.4.0, Build 3038.

**Comment by Maikel-Koek** [comment]
Still an issue at my end!

**Comment by fulldecent** [comment]
Confirming this is still live

**Comment by mr-mmmmore** [comment]
I encounter this problem too and it is quite a pain, sometimes I find myself spending more time fixing the indentations than writing SQL!

Here are my editor settings:

![image](https://user-images.githubusercontent.com/14160945/145072844-e27cbe04-c74a-479f-97ff-2f36422a6af4.png)

Also this is happening a lot more when the query window is loaded with an external sql file.

When reopening SQL code where indentations have been messed up by Sequel Ace in an external editor  I have found that more spaces were present than showed by Sequel Ace.

**Comment by luis-** [comment]
I believe this can be closed, fixed by #1333 but I hadn't linked it properly to this before it was merge.

**Comment by mr-mmmmore** [comment]
Is this fix in the latest version (3.4.4)? Because the problem is still here with it...

**Comment by mfehr94** [comment]
> Is this fix in the latest version (3.4.4)? Because the problem is still here with it...

No this was fixed in the latest beta
