### ISSUE TITLE
Watch Out!! Sometimes the tab name is the wrong connection

### ISSUE THREAD

**Issue by bobbarn** [Sequel-Ace/Sequel-Ace#1207]
- Sequel Ace Version (including build number): 3.3.3  3024
- Sequel Ace Source (App Store/GitHub/Homebrew): App Store
- macOS Version: 11.3.1
- Processor Type (Intel/Apple): 2.3 GHz Quad-Core Intel Core i7
- MySQL Version: 5.7 & 5.8
- macOS Localization: English (US)

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
Didn't see it

**Description**
First of all really appreciate you taking over this project. 
With 3 tabs open. Local, Staging and Production occasionally I find that the tab name and tab connection do not match.
If it helps to know Local is a Docker based Mysql server. Staging and Production are AWS RDS MYSQL 8. All 3 have the exact same schema so if you are not watching the content you can be easily fooled.

**Steps To Reproduce**
1. Open a few tabs connecting to different environments( in my case a 2 RDS instances and a Docker container
2. Have your day jumping back and forth and at some point you may notice the tabs are not representing the correct connection. Luckily I rarely make DB changes using Sequel Ace but if you do you can imagine...
3. Sorry I cannot see an exact action that triggers this but it has happened numerous times.

**Expected Behaviour**
The tab name to always represent the connection and db contents that the name implies.

*

**Comment by Kaspik** [comment]
This has been fixed in 3.4.0.

**Comment by maggiechen** [comment]
I seem to have encountered this issue on 3.4.0 (Build 3038) as well. All of the databases I connect to are Docker MySQL dbs. Same repro steps as op mentioned. 

One thing I noticed is that even though the tab names may be wrong, the tab colour of the connection (the one you can set in the connection details) is correct. So even though the tab that says it's for our Beta environment is actually the tab for my Local environment, it still shows the tab colour of the Local environment.

**Comment by EricSocs** [comment]
Is still an issue in 3.4.5 and just had an issue due to it. Upgrading to 3.5 now.

**Comment by EricSocs** [comment]
Still an issue in 3.5.0.

On VPN, databases accessed through VPN IP.

Had 4 tabs open.
Mac went to sleep, with tab 2 (local database) selected, and other three tabs on various VPN databases.

Upon waking, VPN connection lost.
Database queries are fine in tab 2 (local database).
Reconnected to VPN, switched to tab 1 (remote VPN database)
Wrong database selected in tab 1: actual selected database was not even open!

It appears that the wrongly selected database is one step down from the list (in my case, the database previously open in tab 1 was database_sandbox, but it actually queried the next database in the list, database_staging.

**Comment by Jelte-ten-Holt** [comment]
This has just happened to me on build 4.0.13. Not just once but twice.
