### ISSUE TITLE
Visual Glitches on macOS 14 Sonoma

### ISSUE THREAD

**Issue by bawanyadam** [Sequel-Ace/Sequel-Ace#1841]
- Sequel Ace Version (including build number): 4.0.8 / 20051
- Sequel Ace Source (App Store/GitHub/Homebrew): App Store
- macOS Version: 14 RC1
- Processor Type (Intel/Apple): Apple

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**

- Yes. Issue persists in beta

**Description**
When connecting to a bookmarked database, the UI will not update and hang on the bookmark despite being connected. Once the window is moved with the mouse, or the application leaves the foreground, then brought back, it will update.

**Steps To Reproduce**
1. Open Sequel Ace
2. Connect to a bookmarked database
3. UI will hang in the bookmark interface until the window is moved, or sent to the background/hidden, then brought back

**Expected Behaviour**

Pre Sonoma behavior. After connecting, user will advance you to the database's UI automatically.

**Related Issues**

**Additional Context**

Video of the UI glitch: https://www.dropbox.com/s/jzed3vpy9qkfnpq/sequel-ace-bug.mov?dl=0

**Comment by davecarlson** [comment]
Confirm I see the same here, 14.0 (23A339)

**Comment by Jason-Morcos** [comment]
Super weird
I'm not running Sonoma yet - is this happening 100% of the time?
Is anyone in @Sequel-Ace/all or the broader community running Sonoma yet and able to debug this/attempt a fix?

**Comment by davecarlson** [comment]
> Super weird I'm not running Sonoma yet - is this happening 100% of the time? Is anyone in @Sequel-Ace/all or the broader community running Sonoma yet and able to debug this/attempt a fix?

100% of the time, every time :)

**Comment by gduh** [comment]
> Super weird
> I'm not running Sonoma yet - is this happening 100% of the time?
> Is anyone in @Sequel-Ace/all or the broader community running Sonoma yet and able to debug this/attempt a fix?

@Jason-Morcos  Sorry, but I don't run Sonoma yet. Maybe not for 2 or 3 months.

**Comment by robinkunde** [comment]
Can't look to closely right now, but it looks like the main thread is getting stalled after the connection is established.

**Comment by orchidcode** [comment]
I confirm this issue as well on Sonoma.

**Comment by smithyj** [comment]
same error, 100% recur

**Comment by ties-s** [comment]
I also had this issue, but for me it's been resolved after installing macOS 14 Release Candidate 2

**Comment by Jason-Morcos** [comment]
> I also had this issue, but for me it's been resolved after installing macOS 14 Release Candidate 2

Can anyone else confirm if this is true? 🤞

**Comment by robinkunde** [comment]
I still see the glitches, but curiously, only if the app is in focus.

**Comment by robinkunde** [comment]
Ok, I was able to further isolate it. The following all have to be true for it to happen for me:
* app is in focus
* content tab is selected
* list of filters is empty

Doesn't matter if a table is selected or if the are rows being displayed.

**Comment by davecarlson** [comment]
> > I also had this issue, but for me it's been resolved after installing macOS 14 Release Candidate 2
> 
> Can anyone else confirm if this is true across the board? 🤞

Still occurs in RC2

**Comment by bawanyadam** [comment]
Likewise, original issue still present in RC2/Public release.

**Comment by Jason-Morcos** [comment]
Please try the latest beta and let us know if it's fixed now! It required quite a few changes to threading, but I think I got it

https://github.com/Sequel-Ace/Sequel-Ace/releases

**Comment by davecarlson** [comment]
> Please try the latest beta and let us know if it's fixed now! It required quite a few changes to threading, but I think I got it
> 
> https://github.com/Sequel-Ace/Sequel-Ace/releases

It's resolved it for me, many thanks !

**Comment by robinkunde** [comment]
@Jason-Morcos I can still reproduce the issue by removing all filters from a content tab view. As soon as the container view for the filters collapses/gets hidden, it freezes up.

**Comment by robinkunde** [comment]
Not sure if this is related, but toggling the filters with the button at the bottom of the content tab gives me this glitch.

<img width="120" alt="Screenshot 2023-09-27 at 11 31 14 AM" src="https://github.com/Sequel-Ace/Sequel-Ace/assets/3142400/77d83393-f865-460a-a943-c20b1468152a">

**Comment by Jason-Morcos** [comment]
I can tell you exactly what line it is:
<img width="786" alt="Screenshot 2023-09-27 at 18 59 59" src="https://github.com/Sequel-Ace/Sequel-Ace/assets/10710367/fb1f1311-36a6-4a94-b009-db4a082ed809">

Changing that line to just setFrameSize instead of the full frame fixes the issue, but borks the actual layout.
It's something about setting the origin for that one view. That's the filter container in the DB View.

Honestly, I've spent over 10 hours at this point investigating this issue and attempting fixes and I truly don't have any more time I can spend to investigate here if I'd like to stay happily married and keep my sanity as much as possible.

There's some sort of issue with the rendering engine hanging the view lifecycle update loop due to view constraint conflicts.
The best approach may be to revamp the entirety of the DBView to use actual auto layout constraints instead of legacy autoresizing masks (the same thing I did for the connection view, and for Preferences - https://github.com/Sequel-Ace/Sequel-Ace/pull/505).

Given this is now a much smaller issue (the app doesn't hang 100% on load and now only in the specific set of steps @robinkunde mentioned - by removing all filters from a content tab view - I feel much more comfortable with this issue existing out there.

We really need help on this project. We have some wonderful users who are really able to get to the bottom of the issues, but we need others contributing code PRs. Just take a look at the contribution history - it's a handful of people at most (huge shoutout to the two new first-time contributors yesterday!). I work on this nights and weekends when I can, but it's so difficult to find the time to really address these complex issues. I want to keep Sequel Ace up and running, I use it every day, but ultimately for open source software to succeed sustainably it takes a large set of community members who can actively contribute and push the software forward.

**Comment by samuelbradshaw** [comment]
Thank you for all you do for this project, @Jason-Morcos!

**Comment by ctissier** [comment]
Hello everyone, just in case it helps, same issue here with macOS Sonoma and Sequel Ace 4.0.8(20051) with exactly the same symptoms as everyone else in this thread.

And thank you @Jason-Morcos and all the contributors for keeping up the good work on this usefull app that I use everyday.

**Comment by Jason-Morcos** [comment]
New beta! I couldn't help but spend a bit more time on this 😆 
Please give it a try and let me know if there's any bugs here - https://github.com/Sequel-Ace/Sequel-Ace/releases

**Comment by robinkunde** [comment]
@Jason-Morcos Thank you so much for all your hard work!

**Comment by elosha** [comment]
Good evening, pardon my interruption of your success, but the filter bar now looks like this on Monterey (Mac OS 12.7) 😬

<img width="293" alt="Bildschirmfoto 2023-10-16 um 19 07 30" src="https://github.com/Sequel-Ace/Sequel-Ace/assets/30213185/add11709-7cf2-4fc9-b985-30bce950df4a">

<img width="294" alt="Bildschirmfoto 2023-10-16 um 19 07 38" src="https://github.com/Sequel-Ace/Sequel-Ace/assets/30213185/00138975-b60b-41e5-b020-1289879ed213">

**Comment by Jason-Morcos** [comment]
PRA to fix bugs are welcome! I don't have Monterey to test so I can't reproduce this issue myself.

**Comment by elosha** [comment]
Are you sure? ;) This is not dark mode. It's the only element that dark, controls have bad contrast. Previously the filter bar had the same bg color as the panel that contains the Apply button. Now everything has the color typically used for the bg of an unpopulated MDI window.

I can try to set up a build environment and try to understand what went wrong, but it could take some time and I won't be able to test it on OS 14.
