### ISSUE TITLE
Application doesn't open on Mac (Big Sur)

### ISSUE THREAD

**Issue by benjij** [Sequel-Ace/Sequel-Ace#2165]
Hi there, sorry to report this. Hope it's the right place, i think something similar happened within the last 12 months or so. 

Sequel Ace stopped opening today. Have restarted the laptop twice and re-installed Sequel Ace but get the following errors listed below.

- Source: App Store - assuming it was up-to-date. 
- Big Sur 11.7.10. (i know, i need to upgrade)
- Mac Book Pro (16" 2019)
- 2.6 GHz 6-Core Intel Core i7
- MySQL ?  5.7.32 locally but also MySQL 8 - not really relevant as can't open the application

There was an update two days ago: "New Crowdin updates", maybe related to this?

Symptoms - i click on the icon to open Sequel Pro and get a pop up, which contains an erro report. Pop up screenshot, and error report attached.

*Felt like my machine didn't shut down 100% cleanly earlier but everything else is ok. Haven't used sequel ace for about 18 hours. ~5pm UK time which ties in with the last update. 

Best regards,

[big_sur_error_report.zip](https://github.com/user-attachments/files/18783271/big_sur_error_report.zip)

Ben

Screen shot of initial pop up:
<img width="441" alt="Image" src="https://github.com/user-attachments/assets/236b03cb-464c-41bb-843e-31d125194650" />

Below is the full error report:

- Sequel Ace Version (including build number):
- Sequel Ace Source (App Store/GitHub/Homebrew):
- macOS Version:
- Processor Type (Intel/Apple):
- MySQL Version:
- macOS Localization:

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**

**Description**

**Steps To Reproduce**
1.
2.

**Expected Behaviour**

**Related Issues**

**Additional Context**

**Comment by AreaFifty0ne** [comment]
I have the same issue.

**Comment by Jason-Morcos** [comment]
Sorry about that!

Working on pushing a 4.2.1 release that's again built with the older version of macOS. I had forgotten I jumped back up to latest for 4.2 as I was having some issues getting the build to compile

This is likely the last release that will support Big Sur

**Comment by Jason-Morcos** [comment]
Please try the latest release candidate and let us know if it's fixed now!

https://github.com/Sequel-Ace/Sequel-Ace/releases

**Comment by AreaFifty0ne** [comment]
Unfortunately this fix did not solve the issue.

[error_report.txt.zip](https://github.com/user-attachments/files/18805170/error_report.txt.zip)

**Comment by robinkunde** [comment]
```Dyld Error Message:
  Symbol not found: __ZNSt3__117bad_function_callD1Ev
  Referenced from: /Applications/Sequel Ace.app/Contents/MacOS/../Frameworks/SPMySQL.framework/Versions/A/libmysqlclient.24.dylib
  Expected in: /usr/lib/libc++.1.dylib
 in /Applications/Sequel Ace.app/Contents/MacOS/../Frameworks/SPMySQL.framework/Versions/A/libmysqlclient.24.dylib ```

Did we chance any dependencies?

**Comment by Jason-Morcos** [comment]
We rebuilt all the dylibs to update
But not sure why this specific error would be popping

**Comment by kubik101** [comment]
I am on Big Sur and the 4.2.1 update didn't fix the issue for me.

I can not download the app, any way i can get a working stable version, I rely on this app for my work flow.

**Comment by AreaFifty0ne** [comment]
> I am on Big Sur and the 4.2.1 update didn't fix the issue for me.
> 
> I can not download the app, any way i can get a working stable version, I rely on this app for my work flow.

I found an earlier version here that works.  [https://github.com/Sequel-Ace/Sequel-Ace/releases/tag/production%2F4.1.6-20078](url)

**Comment by robinkunde** [comment]
I tried to get a virtual machine of Big Sur going but my MBP is too new apparently. I only tried UTM tho. A commercial virtualization software might do better.

**Comment by Jason-Morcos** [comment]
Looks like the Big Sur specific issue is resolved, but there's some other issue affecting a broader swath of older macOS versions - Consolidating that discussion to there - https://github.com/Sequel-Ace/Sequel-Ace/issues/2169
