### ISSUE TITLE
TABLE INFORMATION panel size issues and header label strangeness

### ISSUE THREAD

**Issue by lostminds** [Sequel-Ace/Sequel-Ace#477]
- Sequel Ace Version: 2.2.2
- macOS Version: 10.15.7
- MySQL Version: 5.5.37

**Description**
The Table/View information panel shown in the bottom left below the list of tables and views has a couple of issues. May not be top priority, by next time you're looking at the UI, here's some feedback:
- The panel now seems to have fixed proportional height when open (instead of fixed absolute like in Sequel Pro), which means it's usually too big, and it can't be resized as expected. 
- The gray header "TABLE INFORMATION" looks like a static label, but if you click it it turns out you can select it (unclear why, and unlike the same style header "TABLES & VIEWS" at the top)
- If you then click the header it turns out it's now a sort of toggle button as well, toggling the panel to an empty ACTIVITIES state, while also in a sort of buggy way toggling the selection state of the row, leaving the background and text blue/gray/white in cycles.
- If you close the panel using the button at the bottom an empty gap appears above the Filter field at the top of the column.

**Steps To Reproduce**
1. Try resizing the window or Table information panel, click table information header.

**Expected Behaviour**
Have table information panel either be fixed appropriate size or possible to resize. Expect the header to be static inert, with nothing happening if you click it. 

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
Yes, all issues present in latest beta.

**Comment by salvor-hardin** [comment]
Also, table information on the table pane has introduced a couple of bugs in recent versions, included 2.3.0
Datetimes missing on creation / update
Rows are expressed in size everywhere, including here.
<img width="542" alt="nodatetime_incorrectKb" src="https://user-images.githubusercontent.com/40695717/99517889-cc4f3980-2987-11eb-815d-571c585367e9.png">

**Comment by mfehr94** [comment]
@salvor-hardin this should be fixed with #509

**Comment by SumBeam** [comment]
Yes, I've pushed a new fix to that PR for the date formatting

**Comment by lostminds** [comment]
It seems that all that has been fixed is the number and date formatting (#518) not the problems with the panel size or weird selection/toggling behavior this issue is about. Are the other problems this report was about fixed, or are those by design?

**Comment by salvor-hardin** [comment]
I've just installed 2.3.1 and all the issues are still there

**Comment by Kaspik** [comment]
Ohh, I closed this even tho we fixed that for 3.0.0 (next release). Re-opening and putting label back.

That will not fix the sizing of the pane if that is still an issue tho (if it's not fixed already by changes we made) - it will need converting to auto layout, which needs big hierarchy changes unfortunately...

**Comment by lostminds** [comment]
In my opinion you could fix most of the panel size issues by just making it a fixed correct size and not having it scale with the parent view size as it does now. That wouldn't require auto-layout and may be enough for now.

If you want to make it resizable you need to put it into an NSSplitView, bit of a bigger change. That seems to requires auto-layout if you want to use NSSplitViewControllers and be able to hide sections completely as I understand it. But for basic split view size adjusting you don't need auto-layout.

**Comment by Kaspik** [comment]
It is already part of NSSplitView.

**Comment by lostminds** [comment]
Ah, even better, than you can adjust the holding priorities for the different sections in the split view in the xib interface editor, to control how they will be resized (or not) as their parent view is resized.

![Screen Shot 2020-11-20 at 10 50 03](https://user-images.githubusercontent.com/17763524/99786051-5204ed80-2b1e-11eb-9241-08599847b457.jpg)

If it's already a split view I don't understand why it's not resizable the the moment like the other split views in the interface? The cursor doesn't even change to the resizing cursor when hovering over the divider. Perhaps it's set up with a delegate that is always responding NO to splitView:shouldAdjustSizeOfSubview: (https://developer.apple.com/documentation/appkit/nssplitviewdelegate/1455269-splitview) preventing it from resizing.

**Comment by Kaspik** [comment]
I'm still not sure what you mean by the issue itself, this is latest release with no changes... :) Anyways if you can, take a look and open a PR if you think there is something wonky! :)

![2020-11-20 11 10 35](https://user-images.githubusercontent.com/7204168/99788245-1fa8bf80-2b21-11eb-95ad-37cb7f50076b.gif)
