### ISSUE TITLE
Sound plays on menu appearance and on launch

### ISSUE THREAD

**Issue by corecoding** [Sequel-Ace/Sequel-Ace#489]
- Sequel Ace Version: 2.2.2 (2104) and 2.3.0 (2111)
- macOS Version: Catalina and Big Sur
- MySQL Version: 5.6

**Description**
When right clicking in certain areas, a sound is played when the menu appears. Also, when opening Sequel Ace, the same alert sound plays.

**Steps To Reproduce**
1. Go to one of the following: the Query window, or Query results, Content, and Table Info
2. Right click to get the popup menu
3. As said, it also happens when Sequel Ace launches for the first time.

**Expected Behaviour**
No sound is played

**Is Issue Present in [Latest Beta](https://github.com/Sequel-Ace/Sequel-Ace/releases)?**
Not sure

![Screen Shot 2020-11-13 at 2 54 13 PM](https://user-images.githubusercontent.com/3803591/99128785-96453a80-25c0-11eb-9567-19fcb82f3bb6.png)

**Comment by Jason-Morcos** [comment]
This is due to a bundles bug I believe.
We should probably fix this before the 3.0 jump @Sequel-Ace/all

**Comment by Kaspik** [comment]
2.3.1 is out 🚀

**Comment by grigoryosifov** [comment]
Hi, this sound still plays every time when I launch Sequel Ace. However the sound from the context menu seems fixed with 2.3.1.

**Comment by Jason-Morcos** [comment]
@jamesstout @Kaspik reopening this issue as it's reporting still occurring on application open

**Comment by Kaspik** [comment]
I can't repro this anymore. So I'll close this and we will see with 3.0.0 release. (also James is doing a lot of work there)
