### ISSUE TITLE
I can't export the sql

### ISSUE THREAD

**Issue by mechille** [Sequel-Ace/Sequel-Ace#574]
- Sequel Ace Version:3.0.0beta
- macOS Version:11.0.1
- Processor Type (Intel/Apple):apple m1
- MySQL Version:5.7

**Description**
I can't export the sql file. is always warning: No directory selected.
and when I push cancel button.the app is Crash.

**Comment by jamesstout** [comment]
Do you have the crash logs please?

**Comment by Kaspik** [comment]
I'm not able to repro the cancel button crash nor the warning. Is there any chance you could check if Sequel has access to the folder in macOS settings / permissions and give us the crash log?

**Comment by Kaspik** [comment]
I'll close this with no response for now. We also released 3.0.1 to the AppStore with some improvements to file access, so might be fixed already.

**Comment by counteragent** [comment]
I get this same error, have been for a while, not sure what update started it, but it wasn't always this way. Also getting the cancel crash, it just makes all Sequel Ace windows unresponsive and I have to quit. No crash report.
<img width="292" alt="image" src="https://user-images.githubusercontent.com/115916/223192198-3a5cefb2-92b5-4cff-bdd1-84ee78b546aa.png">

**Comment by Jason-Morcos** [comment]
@counteragent Please try changing the export directory like the prompt suggests. It's possible you've got some funky directory access things cached so manually selecting a new export directory (using the file browser and NOT manually entering a directory path) might fix that

**Comment by counteragent** [comment]
@Jason-Morcos that’s exactly what I try to do, but it doesn’t work. The directory field stays blank after choosing one. Also, it won’t even let me manually write a directory. This happens on both of my MacBooks, my old Intel and new M1. The path input is squished and doesn’t show anything 

![D5927479-C5A8-4C72-9292-7BBFCA6C7BD5](https://user-images.githubusercontent.com/115916/223594690-bc92f045-35fd-4b41-ba30-42360ceaab9b.png)

**Comment by jaredmoody** [comment]
In case it helps someone else, I had this same issue on the latest version, 4.0.14. 

Completely removing the app and all support files (I used AppCleaner) and re-installing resolved the issue.

**Comment by wiejakp** [comment]
same issue in:
Version 4.1.3
Build 20074

please, just let the Path field be editable when I click on it...

**Comment by Sam-Xronn** [comment]
Also same issue in; 
Version 4.1.2
Build 20073

**Comment by jpmishra1010** [comment]
Go the solution, if you are using mac:
Go to Settings from Top menu bar after opening Sequel Ace
Then Go to Files
Select the permitted path. 

Voila, now you can export it easily.

**Comment by wiejakp** [comment]
> @Sam-Xronn @justMoritz Go the solution, if you are using mac: Go to Settings(By clicking on Sequel Ace after Apple Icon) from Top menu bar after opening Sequel Ace Then Go to Files Select the permitted path.
> 
> Voila, now you can export it easily.

I don't think this tackles the main cause.

I've observed that this bug happens when trying to import into the directory that i've used in past. I assume that if value is the same as last, it will prevent you from selecting that path again therefore I get my issue. Changing path to other directory and then changing back to the directory i want to use fixed the issue for some time. But it will fail once again in couple of weeks for some reason.

**Comment by mercierj** [comment]
Problem is still here. 
If my previous folder used to store sql/csv files is deleted, path is locked and I cant export.
For example I used to export in ~/Desktop/dbs
I deleted dbs folder -> Cant export anymore, path field is locked and I get error about selecting a path. 
If I create folder again, it's fixed.

**Comment by raychung0520** [comment]
https://github.com/Sequel-Ace/Sequel-Ace/issues/1192
My issue has been solved following this.

**Comment by sts-ryan-holton** [comment]
Still an issue for me

**Comment by rswilem** [comment]
Still happens for me as well, subscribing...

Tried:
- Select folder in Settings > Files > Accessible Files
- Granting Full disk access for Sequel Ace
- Restarting / reinstalling / different paths

**Comment by areeb-011bq** [comment]
1. Go to System Settings by clicking apple icon
2. Then go to Privacy & Security
3. Select Full Disk Access from right menu
4. Click on + icon
5. Enter password and select Applications from left menu
6. Then select Sequel Ace from applications list
7. Quit and reopen Sequel Ace
8. Export sql dump
9. Change path then select downloads
10. Create new folder with desired name (eg. sql-dump)
11. Select that folder, it will add the path in Sequel ACE

Enjoy coding

**Comment by lmgringhuis** [comment]
Adding the folder to Settings > Files > Accessible Files is what helped me. Never had this issue before and doing multiple exports on a weekly basis. Just happened today. The app crashed when trying to select a folder.
