### ISSUE TITLE
The problem of code completion

### ISSUE THREAD

**Issue by bpzhang** [Sequel-Ace/Sequel-Ace#633]
- Sequel Ace Version:  3.0.0 3006
- macOS Version: 10.15.7
- Processor Type (Intel/Apple): Intel
- MySQL Version: 5.7.12

**Description**
  In the case of a query table with an alias, the fields in my code completion prompt would be for the entire database, not the query table
**Steps To Reproduce**
1. I have two tables in db of test.eg: student and teacher
2.I make a query operation ,like this:
`select * from teacher t where t.name='sd'`
and the alias name 't' and I type '.' the the prompt like ：
![image](https://user-images.githubusercontent.com/1734396/102292091-774f1500-3f7f-11eb-86dd-fb73410756ff.png)

**Comment by jamesstout** [comment]
Yeah, here's the code [L457](https://github.com/Sequel-Ace/Sequel-Ace/blob/3b88709cc6e1c95574680a2115776cdc781a6e66/Source/Views/TextViews/SPTextView.m#L457). At this point when using an alias, the aDbName and aTableName do not contain values, so it keeps all the dbs, and scans them. We need a way to figure out  1. if someone entered an alias, 2. why no db name

https://github.com/Sequel-Ace/Sequel-Ace/blob/3b88709cc6e1c95574680a2115776cdc781a6e66/Source/Views/TextViews/SPTextView.m#L436-L470

Also, is there ever a case where a users wants ALL the column names in the entire database? @Sequel-Ace/all

**Comment by jamesstout** [comment]
hmm however: 

https://github.com/Sequel-Ace/Sequel-Ace/blob/3b88709cc6e1c95574680a2115776cdc781a6e66/Source/Views/TextViews/SPTextView.m#L828-L833

Anyway, I'm taking a look.

**Comment by jamesstout** [comment]
Hopefully sorted by #635.

**Comment by Jason-Morcos** [comment]
Fix merged into the upcoming 3.0.1 release

**Comment by bpzhang** [comment]
> Fix merged into the upcoming 3.0.1 release

Good Job  thanks

**Comment by bpzhang** [comment]
> Fix merged into the upcoming 3.0.1 release

the issue is still exists

![image](https://user-images.githubusercontent.com/1734396/102856535-a115a980-4461-11eb-9cfe-d006a0599a3f.png)

**Comment by jamesstout** [comment]
Can't reproduce with the info provided. I just tried, got a single table back...

**Comment by bpzhang** [comment]
> Can't reproduce with the info provided. I just tried, got a single table back...

Do I need to provide any additional information? I have a lot of tables and a lot of databases, could this be the problem? Or is it a conflict caused by an upgrade?

**Comment by bpzhang** [comment]
I completely wiped the app from my computer and reinstalled it and now I don't have the problem

**Comment by jamesstout** [comment]
oh, strange. but thanks for letting us know.
