### ISSUE TITLE
Connection lost after OS goes to sleep - reconnect doesn't work

### ISSUE THREAD

**Issue by cappadaan** [Sequel-Ace/Sequel-Ace#658]
V 3.0.1

> Connect to database
> AFK, OS goes to sleep
> Wake up OS and login
> Click on Sequel Ace icon
> Click on any table in current connected DB
> result

<img width="519" alt="Screenshot 2020-12-19 at 10 17 55" src="https://user-images.githubusercontent.com/25279400/102685861-dca34000-41e3-11eb-9961-ef593f80800e.png">

my setting

<img width="207" alt="Screenshot 2020-12-19 at 10 18 13" src="https://user-images.githubusercontent.com/25279400/102685864-e0cf5d80-41e3-11eb-918d-43cd313a9243.png">

I would except the connection to auto-reconnect or to be alive.

**Comment by Kaspik** [comment]
Thinking about the "Keep connection alive" - Not sure if it's supposed to be "keep it forever even if system says no" or if it's supposed to keep it active while you are working and in the window - possibly even if you are not in the window, but the computer works.

One of the reasons this might be happening is because system tells us "go to sleep" (especially on MacBooks without power adapter connected). Like any others apps (VPN connections for example - these are usually lost too), in that case the connection should be probably dropped (which is apparently).

If "Reconnect" button works, I'll mark this low priority and take a look on it later over the Christmas, but we would basically need to "check connection and reconnect" every time the app becomes active.

**Comment by cappadaan** [comment]
The reconnect option does not work, the same Connection lost popup keeps appearing after using the reconnect button in this situation. Also auto-reconnect in this situation would be very useful.

**Comment by Jason-Morcos** [comment]
Labeling as high priority bug as reconnect button doesn't work

**Comment by matejsp** [comment]
Having the same problem here. Every time my computer goes to sleep it looses the connection and I am unable to reconnect. What's even worse in this case is the loss of Query data. Is there a chance to in case of crash, network problem, bug to restore previous Query contest based on the connection it was linked to.

**Comment by Jason-Morcos** [comment]
> Is there a chance to in case of crash, network problem, bug to restore previous Query contest based on the connection it was linked to.

Please make this a separate GitHub issue in the future for this kind of thing instead of tacking on to this issue. However, the query should be saved to the console (see query console) if the app closes as of 3.0. If you find a case where the query doesn't appear in the console if a specific bug occurs, please open a new issue and we can investigate.

**Comment by needz** [comment]
The issue still exists in 3.0.2

**Comment by matejsp** [comment]
I can confirm that this issue is still in 3.0.2.

**Comment by Kaspik** [comment]
This has not been fixed yet.

**Comment by jamesstout** [comment]
Do we know how long the system has to sleep?

**Comment by jamesstout** [comment]
OK, I can replicate with a VPN, connect and disconnect. I added logging:

Connect via TCP
```log
[27082:1758111] JIMMY _connect`
```
Connect via SSH
```log
[27082:1758128] JIMMY _connect`
```
Disconnect VPN, and wait....
```log
[27082:1758157] Connection 1: encountered error(1:53)
[27082:1758838] JIMMY _disconnect
[27082:1758838] SPMySQL Framework: query cancellation failed because connection failed - 42511
[27082:1758838] JIMMY _unlockConnection
[27082:1758838] JIMMY _cancelKeepAlives
[27082:1758838] JIMMY _lockConnection
[27082:1757751] JIMMY ssh tunnel disconnect
[27082:1757751] JIMMY connectionState == SPMySQLProxyIdle, returning without disconnecting
[27082:1758838] JIMMY ssh tunnel disconnect
[27082:1758838] JIMMY connectionState == SPMySQLProxyIdle, returning without disconnecting
```
Eventually, the reconnect dialog pops up, click reconnect .. erm...:
`[27082:1758838] JIMMY _disconnect`

The close connection **AND** reconnect button are both connected to `(IBAction)closeErrorConnectionSheet`, which just closes the sheet. No attempt to reconnect. Wonder where that code went?

**Comment by jamesstout** [comment]
Oh there's a bit more to it. This is called after the reconnect dialog ... but and the result is passed to the delegate .... down the rabbit hole I go ...

https://github.com/Sequel-Ace/Sequel-Ace/blob/051134abc47cd36a3001d89fb04195a95d22cbb4/Source/Controllers/MainViewControllers/SPDatabaseDocument.m#L6562-L6589

**Comment by jamesstout** [comment]
More logging here: https://pastebin.com/E9NDf21p

Seems like this might be the issue:

`a reconnection attempt is already being made, waiting`

There are hundreds of them, if you keep choosing "reconnect", it's endless.. per the comment:
```objc
/**
 * Calls the private _reconnectAllowingRetries to do this.
 * Error checks extensively - if this method fails, it will ask how to proceed and loop depending
 * on the status, not returning control until either a connection has been established or
 * the connection and document have been closed.
 * /
```

**Comment by jamesstout** [comment]
When the network status changes and you have an ssh connection, it automatically tries to reconnect:

```
JIMMY _proxyStateChange
JIMMY If the connection has actively been used in the last couple of minutes, trigger a full reconnection attempt
JIMMY _reconnectAllowingRetries
JIMMY _disconnect
JIMMY threadCancelled: 0
JIMMY pingElapsedTime: 0.000432
JIMMY _unlockConnection
JIMMY keepAliveLastPingSuccess: 0
```

Then there's another reconnect attempt as `keepAliveLastPingSuccess == 0`:

```
JIMMY !connectionVerified, calling _reconnectAllowingRetries
JIMMY _reconnectAllowingRetries
JIMMY a reconnection attempt is already being made, waiting
JIMMY _unlockConnection
JIMMY _unlockConnection
JIMMY _cancelKeepAlives
JIMMY _lockConnection
JIMMY _unlockConnection
JIMMY ssh tunnel disconnect
JIMMY connectionState == SPMySQLProxyIdle, returning without disconnecting
JIMMY _lockConnection
JIMMY _waitForNetworkConnectionWithTimeout: 10.000000
JIMMY return hostReachable: 1
JIMMY we have a proxy
JIMMY Request that the proxy re-establishes its connection
JIMMY connect in ssh tunnel
JIMMY a reconnection attempt is already being made, waiting
```

Eventually the reconnect dialog pops up, if you click reconnect:

```
JIMMY By default attempt a reconnect
JIMMY _reconnectAllowingRetries
JIMMY _disconnect
JIMMY _lockConnection
JIMMY _waitForNetworkConnectionWithTimeout: 10.000000
JIMMY return hostReachable: 1
JIMMY we have a proxy
JIMMY Request that the proxy re-establishes its connection
JIMMY connect in ssh tunnel
JIMMY a reconnection attempt is already being made, waiting
JIMMY a reconnection attempt is already being made, waiting
JIMMY a reconnection attempt is already being made, waiting
JIMMY a reconnection attempt is already being made, waiting
```

and loop....

I think `proxyStateChange` is called before `Reachability` says there's a network...

**Comment by jamesstout** [comment]
Ultimately, the code calls `mysql_ping` (ref: [mysql_ping](https://dev.mysql.com/doc/dev/mysql-server/latest/mysql_8h.html#afb52359ba100adf315c0b9b9be9943c3))

```c
int STDCALL mysql_ping(MYSQL *mysql) {
  int res;
  DBUG_TRACE;
  res = simple_command(mysql, COM_PING, nullptr, 0, 0);
  if (res == CR_SERVER_LOST && mysql->reconnect)
    res = simple_command(mysql, COM_PING, nullptr, 0, 0);
  return res;
} 
```

However, it's called with the `MYSQL *mySQLConnection;` struct, which doesn't have the ssh details, anyway, it always fails, so triggers another reconnect attempt ...

**Comment by jamesstout** [comment]
built a debug mysql client lib:

```
JIMMY _proxyStateChange
JIMMY FROM MYSQL. In mysql_ping
JIMMY FROM MYSQL. Host: 127.0.0.1
JIMMY FROM MYSQL. DB: tiberius_hkwarnings
JIMMY FROM MYSQL. User: root
JIMMY FROM MYSQL. Host Info: 127.0.0.1 via TCP/IP
JIMMY mysql_ping retcode = 0
```

So I think it's pinging 127.0.0.1, as well as trying to reconnect the proxy. The ping fails, triggering another reconnect attempt...

**Comment by Jason-Morcos** [comment]
> built a debug mysql client lib:
> 
> ```
> JIMMY _proxyStateChange
> JIMMY FROM MYSQL. In mysql_ping
> JIMMY FROM MYSQL. Host: 127.0.0.1
> JIMMY FROM MYSQL. DB: tiberius_hkwarnings
> JIMMY FROM MYSQL. User: root
> JIMMY FROM MYSQL. Host Info: 127.0.0.1 via TCP/IP
> JIMMY mysql_ping retcode = 0
> ```
> 
> So I think it's pinging 127.0.0.1, as well as trying to reconnect the proxy. The ping fails, triggering another reconnect attempt...

Does this mean all we need to do is remove the ping? I'm not sure I understand what the path is to fix!

**Comment by jamesstout** [comment]
> Does this mean all we need to do is remove the ping? I'm not sure I understand what the path is to fix!

At least one of the ping failures triggers the error dialog (reconnect or disconnect). I tried removing it and it goes into an infinite loop. And I was just trying with one connection and couldn't figure out the path. If you have a local TCP connection ... that one doesn't disconnect. 

I was trying to see if any of the controllers had an array of all the connections (`AppController` has an array of `databaseDocs`, which each have a `mySQLConnection`). Then when we are notified of a reachability change, we check to see if it disconnected (that's a whole thing as well .. if it is in the process of disconnecting, it reports connected), if it disconnected and we have a network then try to reconnect. But you need to check for outstanding queries, and cancel them, but you can't cancel as there is no connection. There is background loss of connection, background reconnect, proxy reconnect, full reconnect, limited reconnect. It's a mess.

**Comment by jamesstout** [comment]
As soon as you disconnect the VPN, there's a log:

`Connection 1: encountered error(1:53)`

That I can't track down!

**Comment by jamesstout** [comment]
Seems to be coming from somewhere within Foundation.

Interestingly, it's only emitted when the app is in the background (NSApplicationDidResignActive), however, even in the foreground, the connection is lost and the loops begin.

**Comment by matejsp** [comment]
The issue is still present in 3.1.0. I have lost so many queries because of this issue, because I am not able to copy paste query window when this happens. This is a deal breaker for me.

I have reverted to 3.0.0. I hope to have a working application again.

**Comment by Kaspik** [comment]
Query should be saved in history when app is closed (not when crashes) - isn't that what's happening for you?

We have (hopefully) PR open that could fix this.

**Comment by matejsp** [comment]
Yes queries are saved in Console. But they are saved by the order of execution. You loose formatting, comments and your order of queries in Query window. It also gets mixed with tons of useless queries (for internal meta data fetching). And you get a lot repetitions (for same query). So not really that useful. I have 30 queries in a console that I run at various times.

I have to go through the Console and copy paste queries and reformat them. So this is really annoying with major time loss if I have to do it multiple times a day (every time mac goes to sleep). I now copy paste it to another editor that does not loose my data. But all the additional changes are gone if I forget to do so.

Query window should NEVER auto close. It should be just marked as disconnected and leave open. Imaging going home or to customer site with a laptop and want to use some other DB. You basically loose everything.

**Comment by Kaspik** [comment]
Yeah that's not really how it is designed right now, where query window is specific to tab / connection / DB. I'm already thinking about that but we have just sh** tons of work to do...

The connection will be fixed - that's what this thread is about - so hopefully we will be able to close this. :)

**Comment by cappadaan** [comment]
There is maybe another issue related to this one.

1. open connectie to DB
2. OS goed to sleep
3. Click op app icon and I see the database contents
4. cmd + W to close this connection and window
5. Same popup appears that connection is lost, with option to reconnect

I would except the connection window to just close, and if the connection is lost than everything is fine, the popup should not appear.

**Comment by matejsp** [comment]
Yes this issue is still not resolved for me too (3.1.1).

Rolling back to 2.3.2. Last working version.

**Comment by Kaspik** [comment]
This is related to https://github.com/Sequel-Ace/Sequel-Ace/issues/811 and memory leak happening due to ARC.

Reconnect button should now work tho.

**Comment by matejsp** [comment]
Well in my case the Reconnect button is still not working. When I click on Reconnect it takes around 20 seconds and it displays the same popup over and over again. It is basically the same issue as before. Mac goes to sleep after wake up this issue pops up. When I choose close and select same DB from list of connections it works without a problem. It is interesting that issue appears only on SSH connections. I am now on Big Sur.

**Comment by cappadaan** [comment]
In my case the reconnect button also doesnt work. Im gonna use 2.3.2 for now, this is unworkable for me.

**Comment by Kaspik** [comment]
@jamesstout If you would have some time to dig into this.

**Comment by jamesstout** [comment]
Notes for me:
1.  The reconnect button does nothing, return code not handled. Background reconnect is already running though. I think we need to kill that and call reconnect ourselves. Maybe.
2. The outlet is sort of disconnected. `File's Owner` is `NSObject`, which doesn't have the outlet methods.
3. Why does our Reachability not detect change in Reachability? (new: `AppCenter` reports that `networkStateChanged` - they use roughly the same Reachability)
4. Why does it take 20+ (sometimes over a minute) seconds to display the connection lost dialog?

**Comment by jamesstout** [comment]
WIP: https://github.com/Sequel-Ace/Sequel-Ace/tree/connection-lost

**Comment by Jason-Morcos** [comment]
> WIP: https://github.com/Sequel-Ace/Sequel-Ace/tree/connection-lost

@jamesstout Is this branch a possible fix to the bug? Worth a PR and a beta to see if it fixes it?

**Comment by jamesstout** [comment]
> Is this branch a possible fix to the bug? Worth a PR and a beta to see if it fixes it?

Nope, it's just loads of logging.

I tested out [swift-nio-ssh](https://github.com/apple/swift-nio-ssh) yesterday. It does NOT lose connection when OS goes to sleep of VPN switches  on/off. I'm wondering like @Kaspik if we should re-write the whole connection stuff.

**Comment by cal-zone** [comment]
Perhaps a very quick workaround?

If you could just have the connection self-close when the Mac goes to sleep and not even present the option to reconnect, that would be a huge time saver.

The way it is now, the state leads a user to believe the connection is still active. But then, as soon as you try to do something, nothing happens and you wait… wait… wait… then finally it says it lost its connection and you have to reconnect (which also takes long time and fails).

Though not ideal, all of that would be resolved simply by not surviving sleep at all and forcing me to open a new connection window from the get-go.

**Comment by cappadaan** [comment]
Any news on this one, this makes the app almost unusable.

**Comment by Jason-Morcos** [comment]
> Any news on this one, this makes the app almost unusable.

No update on this one. We haven't been able to fix the issue yet. I would be happy to review a PR aimed at fixing the issue if you have ideas, @cappadaan!

**Comment by cappadaan** [comment]
An option to just auto disconnect and close the connection window if the timeout  occurs would be a temp solution.
the problem now is the popups that appear which cause endless loops and if they work take forever.

**Comment by olimortimer** [comment]
I'm also experiencing the same issue. I recently moved from Sequel Pro to Sequel Ace, with the same connections / setup, yet Sequel Pro didn't have this issue and kept the connection alive. Happy to provide any info required.

**Comment by n9yty** [comment]
Just a note that this is happening here too, although I think it is established at this point that it is a problem. But it makes it somewhat unusable if I am going to lose queries. And they may get thrown in the query history, but the order of queries in there seems almost random at times, hard to find what I was working on. :(. So the query history issue is also still not fixed, because if they aren't in reverse chrono order, it is almost useless as you don't know which was more recent. :( :( :(

**Comment by matejsp** [comment]
The latest version (3.3.0) has the same problem. That's a long time for a critical bug.
In the meantime I have switched to 2.3.2 version. Then I have also tried other programs.
I still prefer Sequel Ace way of handling multiple connections. But yeah ... lack of stability is a deal breaker.

Btw Beekeeper Studio as an alternative is actually quite awesome (cross platform, mysql & postgresql, fast, stable).

**Comment by Kaspik** [comment]
@jamesstout Were you able to continue on that branch please?

**Comment by Alfian5229** [comment]
bug still exist in version 3.3.1

**Comment by fmp777** [comment]
Having the some 'reconnect' issue - mine is triggered when my load-balanced dual-wan switches ISP. App beachballs for an annoying spell, then pops up connection problem, reconnect won't work, have to (annoyingly) go through this process for every single tab - don't have same problem on Sequel Pro

**Comment by johnbettiolMM** [comment]
Funny story.. I only use a mac because I <3 SequelPro (and now am using SequelAce).
Unfortunately this issue is a blocker, I'm really sorry that this problem seems so hard to solve!
I'm not an ObjectiveC/Swift/Mac dev so I can't really offer support here either!

**Comment by matejsp** [comment]
new release 3.3.2, same sad story ... it's already 5 months for such critical bug ... 
lost so many queries and wasted so much time ... gone to toilet, taking a phone call and bam ... all your work is gone ...

went from full time user to occasional user because of this ...

**Comment by johnbettiolMM** [comment]
Is anyone interested in helping me get this running locally and then I just fix it?  I have a holiday coming up, perhaps it's time to learn something new?

I'd just need an idiots guide to:
* What IDE
* How to build 
* How to run locally

If someone's willing to help me get started I can put in some time..

Note: It isn't like I have a shitload of other things to do, but I feel this is so damned annoying and frustrating that it's worth I stop watching twitch streams after-hours and did something for humankind ;)

**Comment by Kaspik** [comment]
Haha - sure! Good luck there. I've started looking at rewriting the whole connection wrapper but we are talking about weeks.

- Download `XCode` (from AppStore if you want)
- Fork this repo and clone it locally
- open the Sequel-Ace.xcworkspace file
- on top left select `Sequel Ace Local Testing`
- on left in Project Navigator you might need to Select project -> Find the Sequel Ace target - Code signing and change this to Sign in locally or Don't code sign (we need to change this to make it easier)
- hit CMD+R to run it locally

For more ideally join our Slack workspace. :)

**Comment by johnbettiolMM** [comment]
I have a week holiday coming, I am going to try convince my wife that I can do some work on it (ie look at this) definitely seems like an impossible task, but it would be nice to do actual code/tech stuff instead of management stuff.

Most likely will fail, but at least it'll be more enjoyable than looking at my disaster of an android app every 6 months ;)

**Comment by UlrichThomasGabor** [comment]
I think this bug is even more severe than just not being able to reconnect.

I've encountered non-deterministic behavior after wakeup, i.e. the same query executed multiple times resulted in (a) correct result, (b) no result, (c) error about malformed package. And I think I even closed the window and reopened a new one, because reconnect is not working, i.e. this was a new connection. Something seems fundamentally broken to me. Maybe related to #811.

I basically restart SequelAce completely now when it has lost its connection, just to be sure I have a proper connection again.

This is a connection via SSH.

**Comment by fmp777** [comment]
I ended up making a local ssh tunnel, then connect ace to localhost which seems to have resolved my issues. so clearly ace has issues handling its ssh db connections

**Comment by vicary** [comment]
Found here because my team had enough of Sequel Pro. Crawled the whole thread and I feel the necessity to thank @jamesstout for the effort of going down the rabbit hole, that's some serious drilling.

Adding to the context here. If I am recalling correctly, one of the nightly builds, about 3 years ago, of Sequel Pro actually reconnects. Because Sequel Pro has been dormant for very, very long time, I only have a rough timeframe here.

I believe Sequel Ace forked way before that, would it by any chance missing a rebase here and there?

**Comment by Jason-Morcos** [comment]
> Found here because my team had enough of Sequel Pro. Crawled the whole thread and I feel the necessity to thank @jamesstout for the effort of going down the rabbit hole, that's some serious drilling.
> 
> Adding to the context here. If I am recalling correctly, one of the nightly builds, about 3 years ago, of Sequel Pro actually reconnects. Because Sequel Pro has been dormant for very, very long time, I only have a rough timeframe here.
> 
> I believe Sequel Ace forked way before that, would it by any chance missing a rebase here and there?

We actually forked off the latest Sequel Pro Nightly (master) prior to starting development! Sequel Pro really had been dead for quite some time, so I think we have all the latest commits from Sequel Pro.
However, I do think it was broken by someone on the Sequel Pro team somewhere between the latest Sequel Pro official release and the last of the nightly builds. There may be an offending PR somewhere in that history that could reveal the issue (there are git tools to isolate such a regression, but I think it's pretty involved). A PR to fix the issue in Ace is certainly welcome if anyone has ideas!

**Comment by MatzeKitt** [comment]
> However, I do think it was broken by someone on the Sequel Pro team somewhere between the latest Sequel Pro official release and the last of the nightly builds.
I can’t confirm that. Otherwise, it wouldn’t had worked in early versions of Sequel Ace, which it did if I remember correctly.

**Comment by Jason-Morcos** [comment]
I think it's never worked in Ace, albeit it may have worsened in attempts to fix it. https://github.com/Sequel-Ace/Sequel-Ace/issues/263

**Comment by matejsp** [comment]
It works/worked in 2.3.2.

**Comment by kozie** [comment]
I'm still having the issues of losing connections and the reconnect option not working.

I'm not on a VPN but using various databases on different servers (thus different connections) through SSH. My mac doesn't go into sleep but having SequelAce running in the background it regularly loses connection when i switch back to SequelAce on a later moment (within a 30 min timespan). All the opened tabs doesn't seem to have a connection anymore.

I do have the 'connection keep-alive' option ticked on.

Using SequelAce 3.4.0 on BigSure 11.4.

**Comment by rickmills** [comment]
Still having this issue on the latest version, it's incredibly frustrating as half the time the app will just lock up and crash. Happens on boty my personal and work mac (both on BigSur)

**Comment by johnbettiol** [comment]
Sadly enough I was so distracted my by crazy child that I didn't even turn on my laptop the entire holiday (so had no chance personally)

I since got a replacement laptop and on this laptop I am running Sequel Pro 1.1.2

Works GREAT!

**Comment by wrmoon** [comment]
I can also confirm that this is still an issue on SequelAce 3.4.0 and BigSur 11.5.  I also have the "connection keep-alive" option checked. To me, this is the biggest annoyance I have with SequelAce.

**Comment by thinbegin** [comment]
I can also confirm this is still an issue with SequelAce version 3.4.0 (build 3038) that is running on Big Sur (version 11.4 and higher).  I do have "connection keep-alive" selected, and am connecting through SSH.

There are a number of reasons this is a huge problem that needs quick attention, ranging from just really bloody annoying to actively disrupting productivity. When SequelAce tries to reconnect, it invariably requires AT LEAST a force-quit of the application, which kills all hope of any "in progress" logging or state saving. There have also been times where it's frozen up more than just the SequelAce application, and had required a full system reboot due to what feels like either runaway memory issues, or thread floods. Not sure which, but it can really be crippling and has lost me lots of work multiple times.

Your efforts are appreciated and acknowledged (and thanked!!!), but if you could please devote some really focused and intensive time on this issue, SequelAce would be on hell of a massive improvement over the old Sequel Pro!  As it stands now though, this issue is big enough that any other improvements (there definitely have been some) just feel more like putting on some lipstick, rather than actual substantive improvement

**Comment by Jason-Morcos** [comment]
I just released a new beta that _may_ fix this issue. We would greatly appreciate if anyone could test this beta and report back whether or not reconnect now works! If it doesn't, I can assure you we'll keep trying to figure it out.

As to the memory leak/slow beach balling that sometimes occurs when connectivity errors happen, I haven't been able to identify the cause of that and we'd greatly appreciate a PR aimed at addressing these issues if someone can figure out their cause.

This is the beta that tries to fix reconnecting, let us know! :)
https://github.com/Sequel-Ace/Sequel-Ace/releases/tag/beta%2F3.4.1-3040

**Comment by vicary** [comment]
@Jason-Morcos wow this doesn't only fix the reconnection button alone, the auto-reconnection has also improved to a level that the button usually doesn't even show up.

**Comment by TimShilov** [comment]
The beta works great for me as well! 🥳

**Comment by thinbegin** [comment]
Question, should the beta version be reading the favorites from my regular
install? If so, it isn't.

**Comment by Kaspik** [comment]
It should not. Different bundle id. You can export them and import into beta. :)

**Comment by thinbegin** [comment]
Awesome, thanks!

**Comment by Jason-Morcos** [comment]
Thank you all for your patience! We'll be including this fix in the 3.4.1 release which should be released this coming week!

**Comment by thinbegin** [comment]
It worked for me too!!!! Nice! Thank you!

**Comment by UlrichThomasGabor** [comment]
@Jason-Morcos I still see weird behavior: Just now I could execute a query (`⌘+R` on `SELECT SUM(status=0), COUNT(*) FROM XYZ`) a few times and received an empty result set until after 10 key presses or so I received the desired sum. A few executions later I received a "lost signal to mysql server" and another execution later I received the result set again. But it definitely works a little better than before.

**Comment by tom10271** [comment]
Can we allow user to disable auto reconnect? When you cannot connect again, just don't reconnect. You cleared all my SQLs and wasted by ~15 seconds on failing to reconnect. I am killing the application with Activity Monitor and restart the application which is even faster.

**Comment by Jason-Morcos** [comment]
> Can we allow user to disable auto reconnect? When you cannot connect again, just don't reconnect. You cleared all my SQLs and wasted by ~15 seconds on failing to reconnect. I am killing the application with Activity Monitor and restart the application which is even faster. 

Please open a new issue for any new feature requests.

**Comment by alfianrehanusa** [comment]
the new release its works for me, thanks

**Comment by samuelbradshaw** [comment]
Because this was broken for so long, every time I come back to Sequel Ace I instinctively expect it to be in the bad state – where it's no longer connected and can't reconnect, and I have to force close and reopen the app and start the connection from scratch again. But over the past month, it's been a sigh of relief – everything just works like it should. I don't have to force-close and reopen the app. It doesn't get disconnected and in a reconnect loop after sitting in the background for a while. I can jump right back in to what I was doing the next day. Thank you so much for figuring out and fixing it!

**Comment by Jason-Morcos** [comment]
> this issue still exists on
> Version 3.5.0
> Build 20029

Many users have reported this issue fixed. Please open a new issue if you're experiencing problems with Sequel Ace and fully fill out the issue template so we have the details we need to investigate - we're happy to dig in more and see if we can figure out what's going on, but I'm fairly confident that _this specific issue_ is already fixed.
