### ISSUE TITLE
Account creation: Schema privileges does not display last added schema

### ISSUE THREAD

**Issue by sebastiansulinski** [Sequel-Ace/Sequel-Ace#723]
This must be one of the latest updates that caused it as I cannot now find the last added schema when adding new user account. Steps to reproduce:

1. Add new database
2. Click Users button in the toolbar, add new Account and navigate to Schema Privileges
3. The last added database is not listed under Schemas

The only way for me to be able to attach privileges to the new database is by re-connecting and going through the user account again.

**Comment by jamesstout** [comment]
What version/build are you using please?

**Comment by jamesstout** [comment]
Just tested:

- [x] 2.3.1
- [x] 3.0.0-3005
- [x] 3.0.0-3006
- [x] 3.0.0-3007
- [x] 3.0.1-3008
- [x] 3.0.2-3010

on mysql (5.5.5-10.5.8-MariaDB-1:10.5.8+maria~focal)

All seem to work.

What server version are you using? thanks

**Comment by sebastiansulinski** [comment]
I'm using MySQL 8 - it was working fine before the last update, but ever since it was updated a few days back there are number of issues - this one being one of them.

**Comment by Kaspik** [comment]
We released 3.1.0 couple of minutes ago, could you please try that?

Also, if some update brings you some issues, try to wipe up the app via AppCleaner (backup favorites) and install it fresh new.

**Comment by sebastiansulinski** [comment]
Thanks @Kaspik - will do.

**Comment by sebastiansulinski** [comment]
Unfortunately the issue persists in v3.1.0. I'll try to capture it and post here shortly.

**Comment by jamesstout** [comment]
Fixed in #840
