### ISSUE TITLE
WARNING - FATAL ERROR: Mixing up Databases

### ISSUE THREAD

**Issue by cord** [Sequel-Ace/Sequel-Ace#978]
- Sequel Ace Version (including build number): Version 3.2.3 Build 3024
- Sequel Ace Source (App Store/GitHub/Homebrew): app store
- macOS Version: 11.2.3
- Processor Type (Intel/Apple): intel

**Description**
Frontend does work on different tab as indicated. Luckily I only worked with read/update queries or reproducible data, otherwise this issue can be fatal

<img width="1813" alt="mailbeez_tracking 2021-03-22 10-43-27" src="https://user-images.githubusercontent.com/158588/111970968-2873c700-8afc-11eb-83da-3baf0967ddbd.png">

Working with several databases on same server. The frontend works on a different database as the visually selected

**Additional Context**
Computer was on sleep

**Comment by Kaspik** [comment]
Hey! Could you please (ideally in read only again) try latest beta 3.3.0? I made a major changes that should either uncover this issue even more for us or fix it completely. :)

**Comment by cord** [comment]
is there a way to import the connection settings from the installed app store version?

**Comment by Kaspik** [comment]
You can either export / import (bottom of favorites - three dots with arrow), or you can probably use the same migration guide as we have from Sequel Pro (https://sequel-ace.com/get-started/migrating-from-sequel-pro.html) just with different names / paths (and skip the keychain part to not remove anything in your AppStore version).

**Comment by cord** [comment]
ok, worked. I will leave the app open with multiple connections and test again tomorrow (as I think the issue might be related to hibernating)

**Comment by cord** [comment]
with beta 3.3.0 all tabs show the correct databasename with running `SELECT DATABASE();`

But as I am not sure how to replicate the issue I can not confirm the issue is solved.

**Comment by Kaspik** [comment]
I'm 99% sure it is, previously it was absolute mess how we worked with tabs, documents and windows, but glad to hear you are not experiencing this anymore now. If you want, stay with the beta in the meantime of course. :)

**Comment by repsher** [comment]
@Kaspik you think your fix would resolve this older issue as well?
https://github.com/Sequel-Ace/Sequel-Ace/issues/349#issuecomment-762390593
Feels like the same kind of issue noted in this ticket. I'm on v3.1.0 now but still occasionally have it happen. I've had to become very OCD when running anything as root toggling DBs to ensure I am indeed running it where I think I am.

**Comment by Kaspik** [comment]
Yes I'm pretty sure it's the same thing and is resolved now. :)

**Comment by Kaspik** [comment]
3.3.0 is out, closing. Let us know if you experience this agin.

**Comment by cord** [comment]
am on 3.3.1 and the issue still appears:

This time it was easy to spot as I worked with different database structures. The Window title matches the content, but the tab does not match. The 2nd tab shows the content of the 3rd tab, and vice versa (there is no "locales" table in the 2nd tab, but the browser shows this content of the locales table):

<img width="1990" alt="locales 2021-05-10 16-47-31" src="https://user-images.githubusercontent.com/158588/117679100-44b4eb80-b1b0-11eb-8ccc-6b55b2de5efe.png">

**Comment by Kaspik** [comment]
https://github.com/Sequel-Ace/Sequel-Ace/issues/1056
